"""empty message

Revision ID: 945449d74be3
Revises: ad20a1faa8b8
Create Date: 2026-04-10 09:43:22.948896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945449d74be3'
down_revision = 'ad20a1faa8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
